version: "3.9"

services:
  db:
    image: postgres:15.1-alpine3.17
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: rpkm67_db
    networks:
      - rpkm67
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  rpkm67:
    name: rpkm67