global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gateway-api
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/api/v1/metrics'